# Generated by Django 6.0.2 on 2026-02-12 03:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_categories_todo_author_todo_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Blog',
        ),
    ]
