# Generated by Django 6.0.2 on 2026-02-15 07:59

import coreapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', validators=[coreapp.models.Blog.validate_image_size]),
        ),
    ]
